### ISSUE TITLE
Why are all the labels in the label folder in the author's pre-processed ACDC dataset all black?

### ISSUE THREAD

**Issue by QianChen113** [xianlin7/ConvFormer#1]
Why are all the labels in the label folder in the author's pre-processed ACDC dataset all black?

**Comment by xianlin7** [comment]
You can read these labels, their values are 0/1/2/3. The value type of the PNG file is uint8 ([0， 255]). It is difficult for the human eye to distinguish 0,1,2,3 from [0, 255].
