### ISSUE TITLE
this model can train multi-class polyp segmentation??

### ISSUE THREAD

**Issue by pervin0527** [xianlin7/ConvFormer#2]
I was looking for a multi-class segmentation model and came across what you created. Is this model capable of segmenting multi-class polyps present in colonoscopy images?

**Comment by xianlin7** [comment]
ConvFormer can be used to replace the transformer blocks in transformer-based or cnn-transformer hybrid models to improve the related models' performance. The number of segmentation categories had no effect on its use.

**Comment by pervin0527** [comment]
> ConvFormer can be used to replace the transformer blocks in transformer-based or cnn-transformer hybrid models to improve the related models' performance. The number of segmentation categories had no effect on its use.

Wow, that's good. thanks to your answer!
