### ISSUE TITLE
RuntimeError: The size of tensor a (784) must match the size of tensor b (256) at non-singleton dimension 3

### ISSUE THREAD

**Issue by gg22mm** [xianlin7/ConvFormer#4]
//
img_channel=3
classes=4
img_size=224
patch_num=16
depth=12 #层数

//训练
device = 'cpu'
epochs=60
model = Setr_ConvFormer(n_channels=img_channel, n_classes=classes, imgsize=img_size,patch_num=patch_num,dim=512,depth=depth,heads=8, mlp_dim=512*4, dim_head=64)
model.to(device)

![图片](https://github.com/xianlin7/ConvFormer/assets/6648329/6c7ec2a5-9136-4390-9e46-6adbf9c0dfb1)

# 报错：
 attn = attn * dis[None, :, :, :]
RuntimeError: The size of tensor a (784) must match the size of tensor b (256) at non-singleton dimension 3

# 我看读取图片太复杂了，应该这样来读取：

//####################### 数据集一 ##################################

base_dir = r'./dataset/4weather'  #data目录 

// 1、获取数据

// 目录
base_dir = r'./dataset/4weather'  #data目录 
train_dir = os.path.join(base_dir, 'train')
test_dir = os.path.join(base_dir, 'test')

//增强方法转换，下面调用此方法，先定义数据增强方法
transform = transforms.Compose([
                  transforms.Resize((224, 224)),            #所有图片转统一大小，大一点会更好，保存模型信息更多
                  transforms.ToTensor()                     #1、转成Tensor格式，2、转换0到1之间,归一化，3、会改变图片的channel放在第一维度上：【batch， channel， hight， width】，所以不能用其它的方式如：plt加载图片
])
// 训练数据-dataset
trainDataset = torchvision.datasets.ImageFolder( # 从图片文件夹中加载数据-返回dataset格式
               train_dir,
               transform=transform
)
// 验证数据-dataset
validDataset = torchvision.datasets.ImageFolder( # 从图片文件夹中加载数据-返回dataset格式
               test_dir,
               transform=transform
)
//查看分类
trainDataset.classes #['cloudy', 'rain', 'shine', 'sunrise'] #查看文件夹，也卞是分类
trainDataset.class_to_idx #{'cloudy': 0, 'rain': 1, 'shine': 2, 'sunrise': 3} #类别编号
len(trainDataset), len(validDataset)#(900, 225)

//dataLoader - 数据切片进行自动分页
batch = 16
trainRow = torch.utils.data.DataLoader(trainDataset, batch_size=batch, shuffle=True)
validRow = torch.utils.data.DataLoader(validDataset, batch_size=batch) #验证测试数据集可以设置大些，因为不做反向传播，占用内存显存比较小

imgs, labels = next(iter(trainRow))

**Comment by gg22mm** [comment]
哦哦，可以了~~

**Comment by ParkourX** [comment]
你好，请问最后如何解决这个问题呢？麻烦教一下谢谢！
