### ISSUE TITLE
即插即用的ConvFormer

### ISSUE THREAD

**Issue by yidamyth** [xianlin7/ConvFormer#6]
作者您好，请问有没有封装好的ConvFormer模块，能够直接基于特征操作，不改变输入输出特征大小和维度，有效的进行特征提取。即插即用可以适用于其他任何模块和任务。

**Comment by MrZhang-YUBO** [comment]
这个恐怕要自己改了，我目前也在尝试拿出来用在其他视觉任务上面

**Comment by yidamyth** [comment]
> 这个恐怕要自己改了，我目前也在尝试拿出来用在其他视觉任务上面

谢谢作者您的回复，如果以后您完善了这个模块，能分享一份那将感激不尽。我自己也下来再学习一下代码。

**Comment by MrZhang-YUBO** [comment]
我不是作者。。纯路人，如果你也在改的话咱们可以交流交流

**Comment by gg22mm** [comment]
> 我不是作者。。纯路人，如果你也在改的话咱们可以交流交流

交流一下，我正在研究图片定位，试了很多模型效果都不太好  QQ 378537908

**Comment by yang123456-mao** [comment]
> 我不是作者。。纯路人，如果你也在改的话咱们可以交流交流

我也在改，可以加个QQ交流一下吗785672216
